/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      colors: {
        'primary':                    '#ffb4ac',
        'primary-container':          '#d22b2b',
        'primary-fixed':              '#ffdad6',
        'primary-fixed-dim':          '#ffb4ac',
        'on-primary':                 '#690007',
        'on-primary-container':       '#ffeeec',
        'on-primary-fixed':           '#410003',
        'on-primary-fixed-variant':   '#93000e',
        'inverse-primary':            '#bb171d',

        'secondary':                  '#c6c6c7',
        'secondary-container':        '#454747',
        'secondary-fixed':            '#e2e2e2',
        'secondary-fixed-dim':        '#c6c6c7',
        'on-secondary':               '#2f3131',
        'on-secondary-container':     '#b4b5b5',
        'on-secondary-fixed':         '#1a1c1c',
        'on-secondary-fixed-variant': '#454747',

        'tertiary':                   '#c7c6c6',
        'tertiary-container':         '#6e6e6e',
        'tertiary-fixed':             '#e3e2e2',
        'tertiary-fixed-dim':         '#c7c6c6',
        'on-tertiary':                '#303031',
        'on-tertiary-container':      '#f3f1f1',
        'on-tertiary-fixed':          '#1b1c1c',
        'on-tertiary-fixed-variant':  '#464747',

        'surface':                    '#131313',
        'surface-dim':                '#131313',
        'surface-bright':             '#3a3939',
        'surface-variant':            '#353534',
        'surface-tint':               '#ffb4ac',
        'surface-container-lowest':   '#0e0e0e',
        'surface-container-low':      '#1c1b1b',
        'surface-container':          '#201f1f',
        'surface-container-high':     '#2a2a2a',
        'surface-container-highest':  '#353534',
        'inverse-surface':            '#e5e2e1',
        'inverse-on-surface':         '#313030',

        'on-surface':                 '#e5e2e1',
        'on-surface-variant':         '#e4beb9',
        'on-background':              '#e5e2e1',
        'background':                 '#131313',

        'outline':                    '#ab8985',
        'outline-variant':            '#5b403d',

        'error':                      '#ffb4ab',
        'error-container':            '#93000a',
        'on-error':                   '#690005',
        'on-error-container':         '#ffdad6',
      },
      fontFamily: {
        headline: ['Lexend', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Lexend', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.25rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
    },
  },
  plugins: [],
};